import Mirage, { faker } from 'ember-cli-mirage'

export default Mirage.Factory.extend({
  name: faker.list.random(
    'apache',
    'bladecenter',
    'check-webinject',
    'check_apache_status',
    'ftp',
    'disk',
    'dns',
    'dhcp',
    'http',
    'http advanced',
    'http content',
    'https',
    'https content auth',
    'ibm_v7000',
    'imap',
    'imaps',
    'imaps_login',
    'interfaces',
    'jabber',
    'junos',
    'mailcleaner_proc',
    'mysql',
    'netapp',
    'netapp_adv',
    'netapp_health',
    'netapp_vol',
    'nrpe',
    'nrpe ssl',
    'ping',
    'pingHost',
    'pop',
    'pops',
    'rhev_datacenter',
    'samba',
    'sftp',
    'smtp',
    'snmp',
    'snmp portstatus',
    'submission',
    'tcp'
  ),
  description: faker.hacker.phrase,
  ipv6:        faker.random.boolean,
  command:     '$USER1$/readmail --rlyfast $ARG1$'
})
