import Mirage, { faker } from 'ember-cli-mirage'

export default Mirage.Factory.extend({
  command: null,
  customer: null,
  name: faker.list.random(
    'apache_idle_worker',
    'bladecenter_power',
    'bladecenter_switches',
    'check_apache_status',
    'check_raid',
    'check_load_by_ssh',
    'check_mysql_health',
    'check_pgsql',
    'check_ram_by_ssh',
    'check_samba',
    'check_symfony',
    'check_tcp_port',
    'check_whois',
    'dhcp',
    'dns',
    'dns_ownname',
    'dns_tcp',
    'ftp',
    'http',
    'http_content',
    'http_tcp',
    'https',
    'https_content',
    'https_content_auth',
    'https_tcp',
    'icingastats',
    'imap',
    'imaps',
    'interface_errors',
    'interface_pps',
    'jabber',
    'ldap_tcp',
    'mysql_tcp',
    'nrpe_cpuload',
    'nrpe_cupsd',
    'nrpe_dhcpd',
    'nrpe_disk',
    'nrpe_disk_backup',
    'nrpe_disk_boot',
    'nrpe_dns',
    'nrpe_docker',
    'nrpe_http',
    'nrpe_https',
    'nrpe_ldap',
    'nrpe_ldap_auth',
    'nrpe_load',
    'nrpe_ping',
    'ping',
    'sftp',
    'smtp',
    'snmp',
    'snmp_uptime',
    'ssh',
    'ssmtp',
    'submission',
    'symonitoring_alert',
    'telnet'
  ),
  description:      faker.hacker.phrase,
  maxCheckAttempts: () => faker.random.number({ min: 1, max:  10 }),
  checkInterval:    () => faker.random.number({ min: 1, max: 120 }),
  retryInterval:    () => faker.random.number({ min: 1, max: 120 }),
  freshness:        () => faker.random.number({ min: 0, max: 600 }),
  isNrpe:           faker.random.boolean,
  alertScheduler:   faker.list.random(null, 1, 2, 3, 4, 5)
})
